src/Sawlux.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sawlux.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Sawlux.Web/Controllers/PratoController.cs
using Sawlux.Data.Contexto;
using Sawlux.Data.Repositorios;
using Sawlux.Service.Services;
using Sawlux.ViewModel;
using Sawluz.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sawlux.Web.Controllers
{
    public class PratoController : Controller
    {
        readonly SawluxContexto contexto;
        readonly IPratoService pratoService;
        readonly IRestauranteService restauranteService;

        public PratoController()
        {
            //TODO: Implementar Unity para DI
            contexto = new SawluxContexto();
            var repo = new PratoRepositorio(contexto);
            var repoRestaurante = new RestauranteRepositorio(contexto);
            restauranteService = new RestauranteService(repoRestaurante);

            pratoService = new PratoService(repo, restauranteService);
        }
        // GET: Prato
        public ActionResult Index()
        {
            var pratos = pratoService.GetAll().ToList();
            var pratosVM = new List<PratoVM>();
            //TODO: Implmentar auto mapper
            foreach (var prato in pratos)
            {
                pratosVM.Add(
                    new PratoVM
                    {
                        Id = prato.Id,
                        Nome = prato.Nome,
                        Preco = prato.Preco,
                        Restaurante = prato.Restaurante.Nome
                    });
            }
            return View(pratosVM);
        }

        public ActionResult Cadastro(int id = 0)
        {
            var prato = new Prato();
            var pratoVM = new PratoCadastroVM();
            if (id > 0)
            {
                prato = pratoService.Get(x => x.Id == id).FirstOrDefault();
                //TODO: Implmentar auto mapper
                pratoVM = new PratoCadastroVM
                {
                    Nome = prato.Nome,
                    Id = prato.Id,
                    Preco = prato.Preco,
                    Restaurante = prato.Restaurante.Nome
                };
            }

            var restaurantes = restauranteService.GetAll()
                      .Select(x => new SelectListItem
                      {
                          Value = x.Id.ToString(),
                          Text = x.Nome,
                          Selected = pratoVM.Restaurante == x.Nome
                      })
                      .ToList();

            pratoVM.Restaurantes = restaurantes;

            return View(pratoVM);
        }

        [HttpPost]
        public ActionResult Cadastro(PratoCadastroVM pratoVM)
        {
            if (ModelState.IsValid)
            {
                var prato = new Prato();
                int restauranteId;
                int.TryParse(pratoVM.Restaurante, out restauranteId);
                //TODO: Implmentar auto mapper
                prato.Nome = pratoVM.Nome;
                prato.Preco = pratoVM.Preco;
                prato.Id = pratoVM.Id;

                pratoService.Cadastro(prato, restauranteId);

                return RedirectToAction("Index");
            }
            return View(pratoVM);
        }

        public ActionResult Delete(int id)
        {
            pratoService.Delete(x => x.Id == id);
            pratoService.Save();
            return RedirectToAction("Index");
        }
    }
}

src/Sawlux.Web/Controllers/RestauranteController.cs
using Sawlux.Data.Contexto;
using Sawlux.Data.Repositorios;
using Sawlux.Service.Services;
using Sawlux.ViewModel;
using Sawluz.Model;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Sawlux.Web.Controllers
{
    public class RestauranteController : Controller
    {
        readonly SawluxContexto contexto;
        readonly IRestauranteService restauranteService;

        public RestauranteController()
        {
            //TODO: Implementar Unity para DI
            contexto = new SawluxContexto();
            var repo = new RestauranteRepositorio(contexto);
            restauranteService = new RestauranteService(repo);
        }
        // GET: Restaurante
        public ActionResult Index(string restaurante)
        {
            var restaurantes = new List<Restaurante>();
            if (!string.IsNullOrEmpty(restaurante))
                restaurantes = restauranteService.Get(x => x.Nome.ToLower().Contains(restaurante.ToLower())).ToList();
            else
                restaurantes = restauranteService.GetAll().ToList();

            var restaurantesVM = new List<RestauranteVM>();
            foreach (var restauranteModel in restaurantes)
            {
                //TODO: Implmentar auto mapper
                restaurantesVM.Add(new RestauranteVM
                {
                    Nome = restauranteModel.Nome,
                    Id = restauranteModel.Id
                });
            }
            return View(restaurantesVM);
        }

        public ActionResult Cadastro(int id = 0)
        {
            var restaurante = new Restaurante();
            if (id > 0)
                restaurante = restauranteService.Get(x => x.Id == id).FirstOrDefault();

            //TODO: Implmentar auto mapper
            var restauranteVM = new RestauranteVM { Nome = restaurante.Nome, Id = restaurante.Id };
            return View(restauranteVM);
        }

        [HttpPost]
        public ActionResult Cadastro(RestauranteVM restauranteVM)
        {
            if (ModelState.IsValid)
            {
                //TODO: Implmentar auto mapper
                var restaurante = new Restaurante();
                restaurante.Nome = restauranteVM.Nome;
                restaurante.Id = restauranteVM.Id;

                restauranteService.Cadastro(restaurante);

                return RedirectToAction("Index");
            }
            return View(restauranteVM);
        }

        public ActionResult Delete(int id)
        {
            restauranteService.Delete(x => x.Id == id);
            restauranteService.Save();
            return RedirectToAction("Index");
        }
    }
}

src/Sawlux.Web/Views/Home/Index.cshtml
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6" style="margin-top:100px">
        <img src="~/Images/lanche.jpg" style="margin-left:50px"/>
        <h3>Sistema de cadastros de restaurantes</h3>
    </div>
    <div class="col-md-3"></div>
</div>

src/Sawlux.Web/Views/Prato/Cadastro.cshtml
@model Sawlux.ViewModel.PratoCadastroVM


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Prato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)


        <div class="form-group">
            @Html.LabelFor(model => model.Restaurante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
                        x => x.Restaurante,
                        new SelectList(Model.Restaurantes, "Value", "Text"), new { htmlAttributes = new { @class = "form-control" } }
    )
                @Html.ValidationMessageFor(x => x.Restaurante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Cancelar", "Index")
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Sawlux.Web/Views/Prato/Index.cshtml
@model IEnumerable<Sawlux.ViewModel.PratoVM>

<p>
    <div class="form-horizontal">
        <h4>Pratos</h4>
        <hr />
        <div class="row">
            <div class="col-md-10">
                @Html.ActionLink("Cadastrar novo prato", "Cadastro")
            </div>
        </div>
    </div>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Restaurante)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurante)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.ActionLink("Editar", "Cadastro", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

src/Sawlux.Web/Views/Restaurante/Cadastro.cshtml
@model Sawlux.ViewModel.RestauranteVM


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurante</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Sawlux.Web/Views/Restaurante/Index.cshtml
@model IEnumerable<Sawlux.ViewModel.RestauranteVM>

<p>
    @using (Html.BeginForm("Index", "Restaurante", FormMethod.Get))
    {
        <div class="form-horizontal">
            <h4>Filters</h4>
            <hr />
            <div class="form-group">
                @Html.Label("Nome", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("restaurante")
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Pesquisar" class="btn btn-default" />
                    @Html.ActionLink("Cadastrar Novo restaurante", "Cadastro")
                </div>
            </div>
        </div>
    }
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Cadastro", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

src/Sawlux.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurante</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Restaurante", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Restaurantes", "Index", "Restaurante")</li>
                    <li>@Html.ActionLink("Pratos", "Index", "Prato")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>